channels:
- anaconda
- conda-forge
dependencies:
- python=3.8.8
- pip:
  - pandas==1.2.5
  - azureml-defaults
  - joblib==0.17.0
  - numpy==1.19.5
  - ipython==7.22.0
  - scikit-learn==1.1.2
  - keras==2.6.0
  - nltk==3.7
  - matplotlib==3.3.4
  - ds-box==1.4.2
  - tensorflow==2.6.0
  - pichle5==0.0.11
  - azure-core==1.26.1
  - azureml==0.2.7
  - azureml-core==1.47.0
name: specialist-model